create extension if not exists "pgcrypto";

create table if not exists public.extra_tips (
  hrac_id uuid primary key references public.hrace(id) on delete cascade,
  winner_tip text not null,
  scorer_tip text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.extra_tip_settings (
  id smallint primary key default 1 check (id = 1),
  lock_at timestamptz not null default '2026-06-11 19:00:00+00',
  winner_actual text,
  scorer_actual text,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.hrace(id) on delete set null
);

insert into public.extra_tip_settings (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.discussion_posts (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.discussion_posts(id) on delete cascade,
  hrac_id uuid not null references public.hrace(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.discussion_reactions (
  post_id bigint not null references public.discussion_posts(id) on delete cascade,
  hrac_id uuid not null references public.hrace(id) on delete cascade,
  emoji text not null,
  created_at timestamptz not null default now(),
  primary key (post_id, hrac_id, emoji)
);

create index if not exists idx_discussion_posts_parent on public.discussion_posts(parent_id, created_at);
create index if not exists idx_discussion_posts_hrac on public.discussion_posts(hrac_id, created_at desc);
create index if not exists idx_discussion_reactions_post on public.discussion_reactions(post_id, created_at);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_extra_tips_updated_at on public.extra_tips;
create trigger trg_extra_tips_updated_at
before update on public.extra_tips
for each row execute function public.touch_updated_at();

drop trigger if exists trg_extra_tip_settings_updated_at on public.extra_tip_settings;
create trigger trg_extra_tip_settings_updated_at
before update on public.extra_tip_settings
for each row execute function public.touch_updated_at();

drop trigger if exists trg_discussion_posts_updated_at on public.discussion_posts;
create trigger trg_discussion_posts_updated_at
before update on public.discussion_posts
for each row execute function public.touch_updated_at();

create or replace function public.ulozit_extra_tipy_secure(
  p_hrac_id uuid,
  p_pin text,
  p_winner_tip text,
  p_scorer_tip text
)
returns json
language plpgsql
security definer
as $$
declare
  v_hrac public.hrace%rowtype;
  v_lock_at timestamptz;
  v_auth json;
begin
  select * into v_hrac from public.hrace where id = p_hrac_id;
  if not found then
    return json_build_object('chyba', 'Hráč neexistuje');
  end if;
  select public.prihlasit_hrace(v_hrac.jmeno, p_pin) into v_auth;
  if v_auth is null or coalesce(v_auth->>'id', '') <> p_hrac_id::text then
    return json_build_object('chyba', 'Neplatný PIN');
  end if;

  select lock_at into v_lock_at from public.extra_tip_settings where id = 1;
  if v_lock_at is null then
    v_lock_at := '2026-06-11 19:00:00+00'::timestamptz;
  end if;

  if now() >= v_lock_at and not coalesce(v_hrac.je_admin, false) then
    return json_build_object('chyba', 'Extra tipy jsou uzamčené');
  end if;

  insert into public.extra_tips (hrac_id, winner_tip, scorer_tip)
  values (p_hrac_id, trim(p_winner_tip), trim(p_scorer_tip))
  on conflict (hrac_id) do update
    set winner_tip = excluded.winner_tip,
        scorer_tip = excluded.scorer_tip,
        updated_at = now();

  return json_build_object('ok', true);
end;
$$;

create or replace function public.admin_upsert_extra_results_secure(
  p_admin_id uuid,
  p_pin text,
  p_winner_actual text,
  p_scorer_actual text
)
returns json
language plpgsql
security definer
as $$
declare
  v_admin public.hrace%rowtype;
  v_auth json;
begin
  select * into v_admin from public.hrace where id = p_admin_id;
  if not found or not coalesce(v_admin.je_admin, false) then
    return json_build_object('chyba', 'Pouze admin');
  end if;
  select public.prihlasit_hrace(v_admin.jmeno, p_pin) into v_auth;
  if v_auth is null or coalesce(v_auth->>'id', '') <> p_admin_id::text then
    return json_build_object('chyba', 'Neplatný PIN');
  end if;

  insert into public.extra_tip_settings (id, winner_actual, scorer_actual, updated_by)
  values (1, nullif(trim(p_winner_actual), ''), nullif(trim(p_scorer_actual), ''), p_admin_id)
  on conflict (id) do update
    set winner_actual = excluded.winner_actual,
        scorer_actual = excluded.scorer_actual,
        updated_by = excluded.updated_by,
        updated_at = now();

  return json_build_object('ok', true);
end;
$$;

create or replace function public.admin_upsert_extra_tip_secure(
  p_admin_id uuid,
  p_pin text,
  p_target_hrac_id uuid,
  p_winner_tip text,
  p_scorer_tip text
)
returns json
language plpgsql
security definer
as $$
declare
  v_admin public.hrace%rowtype;
  v_target public.hrace%rowtype;
  v_auth json;
begin
  select * into v_admin from public.hrace where id = p_admin_id;
  if not found or not coalesce(v_admin.je_admin, false) then
    return json_build_object('chyba', 'Pouze admin');
  end if;
  select public.prihlasit_hrace(v_admin.jmeno, p_pin) into v_auth;
  if v_auth is null or coalesce(v_auth->>'id', '') <> p_admin_id::text then
    return json_build_object('chyba', 'Neplatný PIN');
  end if;

  select * into v_target from public.hrace where id = p_target_hrac_id;
  if not found then
    return json_build_object('chyba', 'Hráč neexistuje');
  end if;

  if nullif(trim(p_winner_tip), '') is null or nullif(trim(p_scorer_tip), '') is null then
    return json_build_object('chyba', 'Je třeba vyplnit vítěze i střelce');
  end if;

  insert into public.extra_tips (hrac_id, winner_tip, scorer_tip)
  values (p_target_hrac_id, trim(p_winner_tip), trim(p_scorer_tip))
  on conflict (hrac_id) do update
    set winner_tip = excluded.winner_tip,
        scorer_tip = excluded.scorer_tip,
        updated_at = now();

  return json_build_object('ok', true);
end;
$$;

create or replace function public.discussion_save_post_secure(
  p_hrac_id uuid,
  p_pin text,
  p_body text,
  p_parent_id bigint default null
)
returns json
language plpgsql
security definer
as $$
declare
  v_hrac public.hrace%rowtype;
  v_new_id bigint;
  v_auth json;
begin
  select * into v_hrac from public.hrace where id = p_hrac_id;
  if not found then
    return json_build_object('chyba', 'Hráč neexistuje');
  end if;
  select public.prihlasit_hrace(v_hrac.jmeno, p_pin) into v_auth;
  if v_auth is null or coalesce(v_auth->>'id', '') <> p_hrac_id::text then
    return json_build_object('chyba', 'Neplatný PIN');
  end if;
  if nullif(trim(p_body), '') is null then
    return json_build_object('chyba', 'Prázdný příspěvek');
  end if;
  if p_parent_id is not null and not exists (select 1 from public.discussion_posts where id = p_parent_id) then
    return json_build_object('chyba', 'Nadřazený příspěvek neexistuje');
  end if;

  insert into public.discussion_posts (parent_id, hrac_id, body)
  values (p_parent_id, p_hrac_id, trim(p_body))
  returning id into v_new_id;

  return json_build_object('ok', true, 'id', v_new_id);
end;
$$;

create or replace function public.discussion_delete_post_secure(
  p_hrac_id uuid,
  p_pin text,
  p_post_id bigint
)
returns json
language plpgsql
security definer
as $$
declare
  v_hrac public.hrace%rowtype;
  v_owner_id uuid;
  v_auth json;
begin
  select * into v_hrac from public.hrace where id = p_hrac_id;
  if not found then
    return json_build_object('chyba', 'Hráč neexistuje');
  end if;
  select public.prihlasit_hrace(v_hrac.jmeno, p_pin) into v_auth;
  if v_auth is null or coalesce(v_auth->>'id', '') <> p_hrac_id::text then
    return json_build_object('chyba', 'Neplatný PIN');
  end if;

  select hrac_id into v_owner_id from public.discussion_posts where id = p_post_id;
  if v_owner_id is null then
    return json_build_object('chyba', 'Příspěvek neexistuje');
  end if;
  if not coalesce(v_hrac.je_admin, false) and v_owner_id <> p_hrac_id then
    return json_build_object('chyba', 'Nelze smazat cizí příspěvek');
  end if;

  delete from public.discussion_posts where id = p_post_id;
  return json_build_object('ok', true);
end;
$$;

create or replace function public.discussion_toggle_reaction_secure(
  p_hrac_id uuid,
  p_pin text,
  p_post_id bigint,
  p_emoji text
)
returns json
language plpgsql
security definer
as $$
declare
  v_hrac public.hrace%rowtype;
  v_auth json;
  v_exists boolean;
begin
  select * into v_hrac from public.hrace where id = p_hrac_id;
  if not found then
    return json_build_object('chyba', 'Hráč neexistuje');
  end if;
  select public.prihlasit_hrace(v_hrac.jmeno, p_pin) into v_auth;
  if v_auth is null or coalesce(v_auth->>'id', '') <> p_hrac_id::text then
    return json_build_object('chyba', 'Neplatný PIN');
  end if;
  if p_emoji not in ('👍','😂','🔥','⚽') then
    return json_build_object('chyba', 'Neplatná reakce');
  end if;
  if not exists (select 1 from public.discussion_posts where id = p_post_id) then
    return json_build_object('chyba', 'Příspěvek neexistuje');
  end if;

  select exists(
    select 1 from public.discussion_reactions
    where post_id = p_post_id and hrac_id = p_hrac_id and emoji = p_emoji
  ) into v_exists;

  if v_exists then
    delete from public.discussion_reactions
    where post_id = p_post_id and hrac_id = p_hrac_id and emoji = p_emoji;
  else
    insert into public.discussion_reactions (post_id, hrac_id, emoji)
    values (p_post_id, p_hrac_id, p_emoji);
  end if;

  return json_build_object('ok', true);
end;
$$;

grant select, insert, update, delete on public.extra_tips to anon;
grant select, insert, update on public.extra_tip_settings to anon;
grant select, insert, update, delete on public.discussion_posts to anon;
grant select, insert, delete on public.discussion_reactions to anon;
grant usage, select on sequence public.discussion_posts_id_seq to anon;
grant execute on function public.ulozit_extra_tipy_secure(uuid, text, text, text) to anon;
grant execute on function public.admin_upsert_extra_results_secure(uuid, text, text, text) to anon;
grant execute on function public.admin_upsert_extra_tip_secure(uuid, text, uuid, text, text) to anon;
grant execute on function public.discussion_save_post_secure(uuid, text, text, bigint) to anon;
grant execute on function public.discussion_delete_post_secure(uuid, text, bigint) to anon;
grant execute on function public.discussion_toggle_reaction_secure(uuid, text, bigint, text) to anon;
