-- v5.1.0 security migration (7. 5. 2026)
-- Aplikovane v Supabase pres MCP (xzlebpzepnhkedlxntgv).
--
-- Co dela:
-- 1) Bcrypt PIN hash (s lazy migraci ze SHA-256)
-- 2) Rate limiting auth_attempts (5 pokusu / 15 min)
-- 3) Validace delek (jmeno 1-32, PIN 4-32, body 1-2000)
-- 4) Account deletion RPC (delete_account_secure - GDPR)
-- 5) Smazani kriticky overpermissive RLS na hrace.DELETE (anon kdokoli mohl mazat hrace)
--
-- DULEZITE: nesahat na gigs_* tabulky - sdilime projekt s GIGS appkou

begin;

-- 1) Smazat overpermissive policy DELETE na hrace
drop policy if exists "anon_delete_hrace" on public.hrace;

-- 2) Helpers
create or replace function public.is_bcrypt_hash(p_value text)
returns boolean
language sql
immutable
as $$
  select coalesce(p_value, '') ~ '^\$2[aby]\$'
$$;

-- 3) Rate limiting tabulka
create table if not exists public.auth_attempts (
  id bigint generated by default as identity primary key,
  jmeno_lower text not null,
  attempt_at timestamptz not null default now(),
  success boolean not null default false
);

create index if not exists idx_auth_attempts_jmeno_at
  on public.auth_attempts(jmeno_lower, attempt_at desc);

alter table public.auth_attempts enable row level security;

drop policy if exists "auth_attempts_no_access" on public.auth_attempts;
create policy "auth_attempts_no_access"
  on public.auth_attempts
  for all
  to anon
  using (false)
  with check (false);

-- 4) Cleanup funkce
create or replace function public.auth_attempts_cleanup()
returns void
language sql
security definer
as $$
  delete from public.auth_attempts where attempt_at < now() - interval '1 hour'
$$;

-- 5) Rate limit check
create or replace function public.check_auth_rate_limit(p_jmeno text)
returns boolean
language plpgsql
security definer
as $$
declare
  v_recent integer;
begin
  select count(*) into v_recent
    from public.auth_attempts
   where jmeno_lower = lower(trim(coalesce(p_jmeno, '')))
     and attempt_at > now() - interval '15 minutes'
     and success = false;
  return v_recent < 5;
end;
$$;

-- 6) prihlasit_hrace - bcrypt aware s lazy SHA-256 migraci
create or replace function public.prihlasit_hrace(p_jmeno text, p_pin text)
returns json
language plpgsql
security definer
as $$
declare
  v_hrac public.hrace%rowtype;
  v_jmeno_clean text := trim(coalesce(p_jmeno, ''));
  v_pin_clean text := trim(coalesce(p_pin, ''));
  v_legacy_hash text;
  v_match boolean := false;
begin
  if length(v_jmeno_clean) = 0 or length(v_jmeno_clean) > 32 then
    return json_build_object('chyba', 'Neplatne jmeno');
  end if;
  if length(v_pin_clean) < 4 or length(v_pin_clean) > 32 then
    return json_build_object('chyba', 'Neplatny PIN');
  end if;

  if not public.check_auth_rate_limit(v_jmeno_clean) then
    return json_build_object('chyba', 'Prilis mnoho pokusu, zkus za 15 min');
  end if;

  select * into v_hrac from public.hrace where jmeno = v_jmeno_clean;
  if v_hrac.id is null then
    insert into public.auth_attempts(jmeno_lower, success) values (lower(v_jmeno_clean), false);
    return json_build_object('chyba', 'Spatne jmeno nebo PIN');
  end if;

  if public.is_bcrypt_hash(coalesce(v_hrac.pin_hash, '')) then
    if extensions.crypt(v_pin_clean, v_hrac.pin_hash) = v_hrac.pin_hash then
      v_match := true;
    end if;
  elsif public.is_sha256_hex(coalesce(v_hrac.pin_hash, '')) then
    v_legacy_hash := encode(extensions.digest((v_pin_clean || 'ms2026salt' || v_jmeno_clean)::bytea), 'hex');
    if v_legacy_hash = v_hrac.pin_hash then
      v_match := true;
      update public.hrace
         set pin_hash = extensions.crypt(v_pin_clean, extensions.gen_salt('bf', 10))
       where id = v_hrac.id;
    end if;
  end if;

  if not v_match then
    insert into public.auth_attempts(jmeno_lower, success) values (lower(v_jmeno_clean), false);
    return json_build_object('chyba', 'Spatne jmeno nebo PIN');
  end if;

  insert into public.auth_attempts(jmeno_lower, success) values (lower(v_jmeno_clean), true);
  return json_build_object('id', v_hrac.id, 'jmeno', v_hrac.jmeno, 'je_admin', coalesce(v_hrac.je_admin, false));
end;
$$;

-- 7) registruj_hrace - bcrypt + validace
create or replace function public.registruj_hrace(p_jmeno text, p_pin text)
returns json
language plpgsql
security definer
as $$
declare
  v_id uuid;
  v_jmeno_clean text := trim(coalesce(p_jmeno, ''));
  v_pin_clean text := trim(coalesce(p_pin, ''));
  v_hash text;
begin
  if length(v_jmeno_clean) < 1 or length(v_jmeno_clean) > 32 then
    return json_build_object('chyba', 'Jmeno musi mit 1-32 znaku');
  end if;
  if length(v_pin_clean) < 4 or length(v_pin_clean) > 32 then
    return json_build_object('chyba', 'PIN musi mit 4-32 znaku');
  end if;

  v_hash := extensions.crypt(v_pin_clean, extensions.gen_salt('bf', 10));

  insert into public.hrace (jmeno, pin_hash)
  values (v_jmeno_clean, v_hash)
  on conflict (jmeno) do nothing
  returning id into v_id;

  if v_id is null then
    return json_build_object('chyba', 'Jmeno jiz existuje');
  end if;

  return json_build_object('id', v_id, 'jmeno', v_jmeno_clean);
end;
$$;

-- 8) auth_hrac_secure_by_id - bcrypt aware
create or replace function public.auth_hrac_secure_by_id(p_hrac_id uuid, p_pin text)
returns hrace
language plpgsql
security definer
as $$
declare
  v_hrac public.hrace%rowtype;
  v_pin_clean text := trim(coalesce(p_pin, ''));
  v_legacy_hash text;
  v_match boolean := false;
begin
  if length(v_pin_clean) < 4 or length(v_pin_clean) > 32 then
    return null;
  end if;

  select * into v_hrac from public.hrace where id = p_hrac_id;
  if v_hrac.id is null then
    return null;
  end if;

  if public.is_bcrypt_hash(coalesce(v_hrac.pin_hash, '')) then
    if extensions.crypt(v_pin_clean, v_hrac.pin_hash) = v_hrac.pin_hash then
      v_match := true;
    end if;
  elsif public.is_sha256_hex(coalesce(v_hrac.pin_hash, '')) then
    v_legacy_hash := encode(extensions.digest((v_pin_clean || 'ms2026salt' || v_hrac.jmeno)::bytea), 'hex');
    if v_legacy_hash = v_hrac.pin_hash then
      v_match := true;
      update public.hrace
         set pin_hash = extensions.crypt(v_pin_clean, extensions.gen_salt('bf', 10))
       where id = v_hrac.id;
      select * into v_hrac from public.hrace where id = p_hrac_id;
    end if;
  elsif public.is_sha256_hex(lower(v_pin_clean)) and lower(v_hrac.pin_hash) = lower(v_pin_clean) then
    v_match := true;
  end if;

  if v_match then return v_hrac; end if;
  return null;
end;
$$;

-- 9) auth_hrac_secure_by_name - bcrypt aware
create or replace function public.auth_hrac_secure_by_name(
  p_jmeno text,
  p_pin_hash text default null,
  p_pin_plain text default null
)
returns hrace
language plpgsql
security definer
as $$
declare
  v_hrac public.hrace%rowtype;
  v_jmeno_clean text := trim(coalesce(p_jmeno, ''));
  v_pin_plain_clean text := trim(coalesce(p_pin_plain, ''));
  v_pin_hash_clean text := lower(trim(coalesce(p_pin_hash, '')));
  v_legacy_hash text;
  v_match boolean := false;
begin
  if length(v_jmeno_clean) = 0 or length(v_jmeno_clean) > 32 then
    return null;
  end if;

  select * into v_hrac from public.hrace
   where lower(jmeno) = lower(v_jmeno_clean)
   limit 1;
  if v_hrac.id is null then
    return null;
  end if;

  if length(v_pin_plain_clean) >= 4 and public.is_bcrypt_hash(coalesce(v_hrac.pin_hash, '')) then
    if extensions.crypt(v_pin_plain_clean, v_hrac.pin_hash) = v_hrac.pin_hash then
      v_match := true;
    end if;
  end if;

  if not v_match and public.is_sha256_hex(v_pin_hash_clean) and lower(coalesce(v_hrac.pin_hash, '')) = v_pin_hash_clean then
    v_match := true;
  end if;

  if not v_match and length(v_pin_plain_clean) >= 4 and public.is_sha256_hex(coalesce(v_hrac.pin_hash, '')) then
    v_legacy_hash := encode(extensions.digest((v_pin_plain_clean || 'ms2026salt' || v_hrac.jmeno)::bytea), 'hex');
    if v_legacy_hash = v_hrac.pin_hash then
      v_match := true;
      update public.hrace
         set pin_hash = extensions.crypt(v_pin_plain_clean, extensions.gen_salt('bf', 10))
       where id = v_hrac.id;
      select * into v_hrac from public.hrace where id = v_hrac.id;
    end if;
  end if;

  if v_match then return v_hrac; end if;
  return null;
end;
$$;

-- 10) discussion_save_post_secure - validace delky body (max 2000)
create or replace function public.discussion_save_post_secure(
  p_hrac_id uuid,
  p_pin text,
  p_body text,
  p_parent_id bigint default null
)
returns json
language plpgsql
security definer
as $$
declare
  v_hrac public.hrace%rowtype;
  v_new_id bigint;
  v_body_clean text;
begin
  v_hrac := public.auth_hrac_secure_by_id(p_hrac_id, p_pin);
  if v_hrac.id is null then
    return json_build_object('chyba', 'Neplatny PIN');
  end if;

  v_body_clean := nullif(trim(coalesce(p_body, '')), '');
  if v_body_clean is null then
    return json_build_object('chyba', 'Prazdny prispevek');
  end if;
  if length(v_body_clean) > 2000 then
    return json_build_object('chyba', 'Prispevek presahl 2000 znaku');
  end if;

  if p_parent_id is not null and not exists (
    select 1 from public.discussion_posts where id = p_parent_id
  ) then
    return json_build_object('chyba', 'Nadrazeny prispevek neexistuje');
  end if;

  insert into public.discussion_posts (parent_id, hrac_id, body)
  values (p_parent_id, p_hrac_id, v_body_clean)
  returning id into v_new_id;

  return json_build_object('ok', true, 'id', v_new_id);
end;
$$;

-- 11) Account deletion (GDPR)
create or replace function public.delete_account_secure(
  p_hrac_id uuid,
  p_pin text
)
returns json
language plpgsql
security definer
as $$
declare
  v_hrac public.hrace%rowtype;
begin
  v_hrac := public.auth_hrac_secure_by_id(p_hrac_id, p_pin);
  if v_hrac.id is null then
    return json_build_object('chyba', 'Neplatny PIN');
  end if;

  delete from public.discussion_reactions where hrac_id = p_hrac_id;
  delete from public.discussion_posts where hrac_id = p_hrac_id;
  delete from public.extra_tips where hrac_id = p_hrac_id;
  delete from public.tipy where hrac_id = p_hrac_id;
  delete from public.hrace where id = p_hrac_id;

  return json_build_object('ok', true);
end;
$$;

grant execute on function public.delete_account_secure(uuid, text) to anon;
grant execute on function public.check_auth_rate_limit(text) to anon;
grant execute on function public.is_bcrypt_hash(text) to anon;
grant execute on function public.auth_attempts_cleanup() to service_role;

commit;
